### ISSUE TITLE
Multidexing crashes

### ISSUE THREAD

**Issue by KamilLelonek** [pocorall/scaloid#111]
Adding `scaloid` in any version to project causes multidexing problems, any class form application cannot be found.

    dependencies {
        classpath "com.android.tools.build:gradle:1.0.0-rc1"
        classpath "jp.leafytree.gradle:gradle-android-scala-plugin:1.3.1"
    }

    java.lang.RuntimeException: Unable to instantiate application com.example.main.MainApplication:     java.lang.ClassNotFoundException: 
    Didn't find class "com.example.main.MainApplication" 
    on path: DexPathList[[zip file "/data/app/com.example.main-2.apk"],
         nativeLibraryDirectories=[/data/app-lib/com.example.main-2, 
         /system/lib]]

**Comment by pocorall** [comment]
I am not fully identify the problem you posted. Can you provide more information and reproducible example?

**Comment by DavidPerezIngeniero** [comment]
I would close the issue, as I don't need multidexing any more, because Android tools have been improved.

**Comment by KamilLelonek** [comment]
I can't tell you what was wrong that time right now, I dropped scaloid for that project.
