### ISSUE TITLE
Problem during compile

### ISSUE THREAD

**Issue by Morgaroth** [pocorall/scaloid#113]
I followed Builiding Scaloid wiki page, I've installed API 10 in android_home folder, evironment setted, and I can''t compile commons:

version 3.6.1
sbt scaloid:generate
sbt +publishLocally

and I get compile error

```
[info] 	delivering ivy file to /home/mateusz/projects/scaloid/scaloid-util/target/scala-2.10/ivy-3.6.1-10.xml
[error] /home/mateusz/projects/scaloid/scaloid-common/src/main/scala/org/scaloid/common/preferences.scala:144: ']' expected but '.' found.
[error]         case v: Array[android.os.Parcelable] => i.putExtra(name, v)
[error]                              ^
[error] /home/mateusz/projects/scaloid/scaloid-common/src/main/scala/org/scaloid/common/preferences.scala:144: ']' expected but '.' found.
[error]         case v: Array[android.os.Parcelable] => i.putExtra(name, v)
[error]                              ^
```
Could You tell me why ? And what I can do for resolve this problem ? remove fragment od template?

**Comment by pocorall** [comment]
It is run with `sbt publishLocal`.

What the `+` character does?

**Comment by Morgaroth** [comment]
http://www.scala-sbt.org/0.13/docs/Cross-Build.html

+ character enables cross biulding against all scala versions defined in crossScalaVersions in build.sbt so this isn't really a problem :) or I'm missing some thing about internals of project :)

**Comment by Morgaroth** [comment]
I think, that problem is with imports ? `android.os.Parcelable` doesn't exist in imported namespace ?

I compile project after removing this part of code (handling arrays).

**Comment by pocorall** [comment]
Thank you for the link! 
I tried to search it, but that kind of character is not easily searchable.

Anyway, I started using some macro features that only supported from Scala 2.11. I forgot to remove 2.10 from `crossScalaVersions`. I will fix it now.

**Comment by pocorall** [comment]
Hmm... I was wrong. It definitely not related with macros.
I don't know why the type `Array[android.os.Parcelable]` in pattern-matching is not possible in Scala 2.10 compiler. Anyway, I dropped 2.10.

**Comment by Morgaroth** [comment]
I look more at this today evening (in GMT+1)  :)
