### ISSUE TITLE
Whenever connecting to websocket ,application is stopping

### ISSUE THREAD

**Issue by amitprasadom** [pocorall/scaloid#115]
package scaloid.example

import android.util.Log
import de.tavendo.autobahn.{WebSocketException, WebSocketConnection, WebSocket, WebSocketConnectionHandler}
import org.scaloid.common._
import android.graphics.Color

class HelloScaloid extends SActivity {
 var msgTextBox :SEditText=null
  var connectBtn:SButton=null
  var contentFromServer:SEditText=null
  var sendMsgBtn:SButton=null
  val mConnection: WebSocket = new WebSocketConnection
  onCreate {
    contentView = new SVerticalLayout {
      style {
        case b: SButton => b.textColor(Color.BLUE)
        case t: STextView => t textSize 10.dip
        case e: SEditText => e.backgroundColor(Color.WHITE)
      }

      this += new SVerticalLayout {
        connectBtn=SButton("Connect to Server",start)

      }.wrap

    this += new SLinearLayout {
      msgTextBox = SEditText("Message")
      sendMsgBtn=SButton("Send Message",sendMsg)
    }.wrap

      this += new SVerticalLayout() {
       contentFromServer
      }.wrap

    } padding 50.dip

}
  private def start {
    val wsuri: String = "wss://xxx.in/websocket"

    try {
      mConnection.connect(wsuri,  new WebSocketConnectionHandler() {
      override def onOpen
      {
        toast("Connected")
      }
      override def onTextMessage(payload: String)
      {
        toast("In message")
      }
      override def onClose(code: Int, reason: String)
      {
        toast("Connectio Lost")

      }

    })
      toast("running")
    }
    catch {
       case e: WebSocketException => {
        alert("Error",e.getMessage)
        }
       }
  }
   def sendMsg{
      mConnection.sendTextMessage("{\"msg\":\"xxx\"}")
   }

}

**Comment by pocorall** [comment]
I would close this issue, because the topic is not related with some specific technical issues of Scaloid.
