### ISSUE TITLE
How to bind SEditText to  SScrollView  ? 

### ISSUE THREAD

**Issue by amitprasadom** [pocorall/scaloid#116]
dataTxtBox.setText(dataTxtBox.getText + "\n" + payload)
   scrollview.smoothScrollTo(0, dataTxtBox.getBottom)
I am trying this code but throwing error

**Comment by pocorall** [comment]
This is not a place posting questions. Use this for suggesting improvements.

**Comment by amitprasadom** [comment]
sorry next time i will keep in mind .but can u please fix this problem for me .thank you

**Comment by Firfi** [comment]
Don't do this they breed that way
