### ISSUE TITLE
Scaloid Demo App looks huge and pixelated on Tablets

### ISSUE THREAD

**Issue by phdoerfler** [pocorall/scaloid#127]
git clone https://github.com/pocorall/hello-scaloid-sbt
    cd hello-scaloid-sbt
    sbt run
Results in:
![very pixelated appearance](https://cloud.githubusercontent.com/assets/163428/7140263/6487ee82-e298-11e4-9731-0f51805fcfd5.png)
![graphical glitches in the auto correct popup](https://cloud.githubusercontent.com/assets/163428/7140281/79202a9e-e298-11e4-9cbe-e7dda7518677.png)
![pixelated toasts](https://cloud.githubusercontent.com/assets/163428/7140294/84a53bd4-e298-11e4-9688-64773d383001.png)

The emulated device (same effect on real tablets) is a Nexus 7 (2012).

**Comment by wookietreiber** [comment]
I have had the same issue, too. The thing is that the demo does not bother with the screen support setting in the manifest, e.g.:

```xml
<supports-screens android:largeScreens="true" android:xlargeScreens="true" />
```

**Comment by phdoerfler** [comment]
For the reference, this is what it looks now:
![Screenshot after fix](https://cloud.githubusercontent.com/assets/163428/7159695/fd5cca10-e351-11e4-879b-8de32fda6f35.png)
