### ISSUE TITLE
TypedResource(TR) Reload

### ISSUE THREAD

**Issue by spidfire** [pocorall/scaloid#131]
is there a way to recreate the TR without running the compiler because I get blocked if I try to refactor some things. 

Example:
-- Original state
```
val a = findViewById(R.id.backgroundView).asInstanceOf[com.android.volley.toolbox.NetworkImageView]
```

--- After refactor
```
val a = findView(RT.backgroundView)
```

But it fails because there are more than one types of backgroundView's in my app

So I started refactoring them to one type but I need to complile to get the new version of TR but I can't compile because I have the old version of TR  (deadlock style)

Is there some way to invoke the creation of the TR?

**Comment by pocorall** [comment]
Scaloid does not create TR. Did you intended to ask a question to writer of TR generator? It depends on which build tool you use.
