### ISSUE TITLE
SArrayAdapter cannot be added to after initialization

### ISSUE THREAD

**Issue by Mause** [pocorall/scaloid#132]
See https://stackoverflow.com/questions/3200551/unable-to-modify-arrayadapter-in-listview-unsupportedoperationexception for details

TL;DR: Android's `ArrayAdapter` must be initialized with a `List` if you want to be able to add items after initialization. The `SArrayAdapter` class forces Array use

EDIT: By added to I mean with `ArrayAdaper.add` and `ArrayAdapter.addAll`

**Comment by pocorall** [comment]
Thanks for reporting!

**Comment by Mause** [comment]
Thanks for fixing!
