### ISSUE TITLE
java.lang.IllegalArgumentException: Lint

### ISSUE THREAD

**Issue by IntelligyScience** [pocorall/scaloid#133]
Hi,

this is a good tool. And a few weeks ago I build a test application. This works fine.
NOW I got an error with a new project.
[error] (compile:compile) java.lang.IllegalArgumentException: Lint must be invoked with the System property com.android.tools.lint.bindir pointing to the ANDROID_SDK tools directory

I am using a Ubuntu 64bit OS.
What is wrong? It seems a missconfiguration. Do someone have an idea?

**Comment by pocorall** [comment]
That issue might not be related with Scaloid. I guess that something is wrong with ANDROID_SDK or lint configuration. Please refer to 355th line of the android source code below:

https://android.googlesource.com/platform/tools/base/+/f97a4fc29268c7f0ad4bd9434e30c5feff19c683/lint/libs/lint-api/src/main/java/com/android/tools/lint/client/api/LintClient.java

**Comment by IntelligyScience** [comment]
Thanks that helps
