### ISSUE TITLE
Broken inheritance between S[...] objects (like SView or SLinearlayout)

### ISSUE THREAD

**Issue by AntoineMorand** [pocorall/scaloid#138]
Hello,

When i tried to create a general trait to mix with Views:
```scala
trait CleverTraitToMix extends SView {
  backgroundColor = 0xFFFF0000
}

class MixedClass extends SRelativeLayout with CleverTraitToMix
```

I encountered the following compilation error telling me that there is no "parent-child" relationship between SView and SLinearLayout as there is between RelativeLayout and View in the standard android hierarchy:

```
[error] D:\AutoConsult\src\e_consult\formBuilder\CleverTraitToMix.scala:10: illegal inheritance; superclass SRelativeLayout
[error]  is not a subclass of the superclass SView
[error]  of the mixin trait CleverTraitToMix
[error] class MixedClass extends SRelativeLayout with CleverTraitToMix {
```
Would it be possible to restore this inheritance relation? Alternatively, is there another way to make mixins between S[...] objects?

**Comment by pocorall** [comment]
As I wrote at readme.md 
https://github.com/pocorall/scaloid#extending-view-class

Try inherit TraitView trait.
