### ISSUE TITLE
broadcastReceiver function for String argument inconsistent with the function taking IntentFilter

### ISSUE THREAD

**Issue by MaciejG** [pocorall/scaloid#139]
in the readme there is an example of using broadcastReceiver function:
```scala
broadcastReceiver(ConnectivityManager.CONNECTIVITY_ACTION) { (context, intent) =>
  doSomething()
}
```

the problem is that it is impossible to use this version of the function this way because the passed onReceiveBody function is parameterless and than it is invoked in onReceive without any parameters:
```scala
  def broadcastReceiver(filterString: String)(onReceiveBody: => Any)(implicit ctx: Context, reg: Registerable) {
    val receiver = new BroadcastReceiver {
      def onReceive(context: Context, intent: Intent) {
        onReceiveBody
      }
    }
    val filter = new IntentFilter()
    filter.addAction(filterString)
    reg.onRegister(ctx.registerReceiver(receiver, filter))
    reg.onUnregister(ctx.unregisterReceiver(receiver))
  }
```

so the only version that takes context and intent parameters is the one which takes filter: IntentFilter as parameter:
```scala
  def broadcastReceiver(filter: IntentFilter)(onReceiveBody: (Context, Intent) => Any)(implicit ctx: Context, reg: Registerable) {
    val receiver = new BroadcastReceiver {
      def onReceive(context: Context, intent: Intent) {
        onReceiveBody(context, intent)
      }
    }
    reg.onRegister(ctx.registerReceiver(receiver, filter))
    reg.onUnregister(ctx.unregisterReceiver(receiver))
  }
```

so this is e.g. possible:
```scala
broadcastReceiver(new IntentFilter(ConnectivityManager.CONNECTIVITY_ACTION)) { (context, intent) =>
  doSomething()
}
```
but the version with String as param may be used only in this way:
```scala
broadcastReceiver(ConnectivityManager.CONNECTIVITY_ACTION) {
  doSomething()
}
```

**Comment by liskin** [comment]
I just lost 3 hours fighting this crap. Even the very example from the README doesn't work! `broadcastReceiver(ConnectivityManager.CONNECTIVITY_ACTION) { (context, intent) => ... }` calls the String/Any version of the function, since ((Context, Intent) => Unit) <: Any, but just evaluating the function does nothing at all. :-(

**Comment by pocorall** [comment]
Sorry for the inconsistence, I've just updated the document.
