### ISSUE TITLE
STextView "here" not working with textSize defined

### ISSUE THREAD

**Issue by MaciejG** [pocorall/scaloid#140]
I have a field defined as follows outside of the onCreate function:
```scala
lazy val powerCableStateText = new STextView("Power cable state") textSize 20.dip
```

the problem is that when added to parent with:
```scala
powerCableStateText.here
```

the text size is not reflected. what works is:

```scala
this += powerCableStateText
powerCableStateText textSize 20.dip
```

when I change the type of the view of powerCableStateText to e.g. SButton or SEditText like this

```scala
lazy val powerCableStateText = new SButton("Power cable state") textSize 20.dip
```
and add it with "here" function, the text size in the button is as expected - meaning 20

**Comment by pocorall** [comment]
Are you testing on HelloScaloid example?

It applies `style { case t: STextView => t textSize 10.dip }` after you initialize `powerCableStateText`. Try again without style statement.
