### ISSUE TITLE
API 8, 9 support using Scala 2.10 and Scaloid 3.3

### ISSUE THREAD

**Issue by 1ambda** [pocorall/scaloid#141]
It seems that Scaloid 3.4 requires minSDK 10 and Scala 2.11.x is incompatible with API Level 8.

- http://blog.scaloid.org/2014/05/scaloid-34-is-released.html
- http://blog.scaloid.org/2014/04/android-api-8-is-incompatible-with.html

Is it possible to support API Level 8, 9 devices using Scala 2.10 and Scaloid 3.3?

**Comment by pocorall** [comment]
Scala 2.11 is released more than a year ago, so I believe most of the Scala library is released for Scala 2.11; And market share of Froyo is just 0.2%, which is surely insignificant.

http://developer.android.com/intl/ko/about/dashboards/index.html

I strongly recommend to target Scala 2.11 and Android API 10. Currently, I have no plan to support older APIs again.

**Comment by 1ambda** [comment]
Thank for reply @pocorall. :)

Our team is currently working with an android client library which has no dependency. (seriously, except the Apache HttpClient included in Android Runtime until 5.x) So, I think Scala dependencies doesn't matter in this case. 

But I was just wondering if there is a incompatibility related with language itself like [Android API 8 is Incompatible with Sacla 2.11](http://blog.scaloid.org/2014/04/android-api-8-is-incompatible-with.html) (I'v searched scaloid issues, but did't find yet)

I think your comment on this issue will be helpful for others who want to support Froyo and Gingerbread. (e.g library developers)

I will close the issue. Thank you again.

**Comment by pocorall** [comment]
You can build your own version of Scaloid by changing the Scala and Android API version. I think that it will work normally, but you might come across some other unknown issues. I was decided to raise target Android API after I found the issue you cited, because struggling with this kind of issues are not meaningful in a longer term.
