### ISSUE TITLE
problem code `def >> : V = v`

### ISSUE THREAD

**Issue by WeiChou** [pocorall/scaloid#144]
When i review the source code, i found a problem:
```
class LayoutParams ... {
    ....
    def >> : V = v
}
```

i think `def >> : V = v` must be treated like this:
```
def >> : V = {
    v.setLayoutParams(this);
    v
}
```
to ensure view perform `requestLayout()`, or the changes will not be applied when set after inited.

**Comment by pocorall** [comment]
It already does in the constructor of `LayoutParams`:

https://github.com/pocorall/scaloid/blob/a3c1c953e750f204af9e0bc594d7cf3f177433c0/scaloid-common/src/main/scala/org/scaloid/common/widget.scala#L1618

**Comment by WeiChou** [comment]
I know, but it's not enough, e.g:
```
SButton("Add padding top").onClick((v: android.view.View) => {
    val b = v.asInstanceOf[SButton]
    b.<<.marginTop(b.<<.topMargin + 5.dip).>>
    meToo.text = b.text + ": " + b.<<.topMargin.toString
}).fw
```
the code doesn't work correctly, i must add `requestLayout()` like this:
`b.<<.marginTop(b.<<.topMargin + 5.dip).>>.requestLayout()`
so i think
```
def >> : V = {
    v.setLayoutParams(this)
    v
}
```
is a good idea, hope you can adopt.

**Comment by pocorall** [comment]
Good idea, I just pushed it.

**Comment by WeiChou** [comment]
perfect.
