### ISSUE TITLE
How to dynamically add view components to SLinearLayout or SVerticalLayout

### ISSUE THREAD

**Issue by darmie** [pocorall/scaloid#145]
Hi, I am a bit new to Scala. But I want to know if it's possible to dynamically add child components to  `SLinearLayout` 

I am trying to achieve something like this 
```scala
val btn = SButton("Help", openUri("http://help.url"))

val layout = new SLinearLayout{
}

//is something like this possible?
layout.addChild(btn)
```

**Comment by pocorall** [comment]
`layout += btn` does that.
