### ISSUE TITLE
Performence issue of Scala on android (may not be related to scaloid)

### ISSUE THREAD

**Issue by doofin** [pocorall/scaloid#153]
Sorry if this is irrelevant,I really love Scala but I have noticed considerable slow down (an activity takes long time to show comparing to kotlin) , here is the setting I use  : https://github.com/doofin/scala4Android

This is quite confusing,What could be the possible reason?

**Comment by pocorall** [comment]
Yes, it seems somewhat irrelevant with Scaloid :-)

Fortunately, I found a possible hiccup point in your project settings: Try remove protify. It can cause significant delay in debug build.

**Comment by doofin** [comment]
This is the issue,thanks!
