### ISSUE TITLE
In the documentation, talk about TypedResource

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [pocorall/scaloid#99]
Instead of using:

    val but = find[Button](R.id.myButton)

it is safer to use:

    val but = findView(TR.myButton)

http://fxthomas.github.io/android-plugin/tutorial/annex-a-using-scala.html

**Comment by pocorall** [comment]
Since there are no further discussion, I'd like to follow the rationale I posted lastly, and consider this issue can be closed.
